<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mujoco_ros2_plugins</name>
  <version>0.1.0</version>
  <description>Plugins for mujoco_ros2_control that simulate real hardware interface features, for any robot</description>
  <author email="adityakamath@live.com">Aditya Kamath</author>
  <maintainer email="adityakamath@live.com">Aditya Kamath (Kamath Robotics)</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_srvs</depend>
  <depend>pluginlib</depend>
  <depend>mujoco_vendor</depend>
  <depend>mujoco_ros2_control_plugins</depend>
  <exec_depend>mujoco_ros2_control</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
